AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SSM Parameters

# Option one ssm dynamic references https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html
# Option two secrets manager
Parameters:
  DbEngine:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /myApp/DbEngine

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Runtime: nodejs16.x
      Handler: app.lambdaHandler
      Environment:
        Variables:
          DB_ENGINE: !Ref DbEngine
          DB_VERSION: '{{resolve:ssm:/myApp/DbVersion:1}}' # SSM requires version
          DB_NAME: '{{resolve:secretsmanager:/myApp/DbName}}'
          DB_USERNAME: '{{resolve:secretsmanager:/myApp/DbCreds:SecretString:Username}}'
          DB_PASSWORD: '{{resolve:secretsmanager:/myApp/DbCreds:SecretString:Password}}'