AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Secrets for my application

Parameters:
  DbEngine:
    Type: String
    Description: DB Engine
    Default: MySQL
    
  DbVersion:
    Type: String
    Description: DB Version
  
  DbName:
    Type: String
    Description: Name of DB to use
    NoEcho: true
    
  DbUsername:
    Type: String
    Description: Username for DB
    NoEcho: true
    
  DbPassword:
    Type: String
    Description: Password for DB
    NoEcho: true

Resources:
  DbEngineParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /myApp/DbEngine
      Type: String
      Value: !Ref DbEngine
      
  DbVersionParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: /myApp/DbVersion
      Type: String
      Value: !Ref DbVersion

  DbNameParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /myApp/DbName
      SecretString: !Ref DbName

  DbCredsParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /myApp/DbCreds
      SecretString: !Sub "{\"Username\":\"${DbUsername}\",\"Password\":\"${DbPassword}\"}"
    