
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template Repo

Resources:
  NodeBaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      # LayerName: NodeBaseLayer
      Description: Base layer for node apps (AWS-SDK, Axios)
      ContentUri: node-base/
      # CompatibleRuntimes: 
      #   - nodejs12.x
      # LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs12.x
      
  NodeBaseLayerPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref NodeBaseLayer
      Principal: !Ref AWS::AccountId
      
  NodeUtilitiesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Utilities layer for node apps (lodash, moment)
      ContentUri: node-utilities/
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs12.x
      
  NodeUtilitiesLayerPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref NodeUtilitiesLayer
      Principal: !Ref AWS::AccountId
      
  PythonBaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Base layer for python apps (boto3, requests)
      ContentUri: python-base/
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
      
  PythonBaseLayerPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref PythonBaseLayer
      Principal: !Ref AWS::AccountId
      
Outputs:
  NodeBaseArn:
    Description: Layer Version ARN for node base
    Value: !Ref NodeBaseLayer
  NodeUtilitiesArn:
    Description: Layer Version ARN for utilities base
    Value: !Ref NodeUtilitiesLayer
  PythonBaseArn:
    Description: Layer Version ARN for python base
    Value: !Ref PythonBaseLayer