PRODUCT_NAME = SwiftApi
DEPS = libswiftCore.so libswiftGlibc.so libswiftDispatch.so libdispatch.so libBlocksRuntime.so libFoundation.so libicui18nswift.so.65 libicuucswift.so.65 libicudataswift.so.65

ifeq ($(ARTIFACTS_DIR),)
  include ../shared.mk
else
  include $(ARTIFACTS_DIR)/../../../shared.mk
endif
